const data = {
  products: [
    {
      _id: "1",
      name: "Nike Plain T-Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/p1.jpeg",
      price: 199,
      countInStock: 40,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Cloth",
    },
    {
      _id: "2",
      name: "Nike Track Pants",
      slug: "nike-pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 430,
      countInStock: 39,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Pant Cloth",
    },
    {
      _id: "3",
      name: "Addidas Plain T-Shirt",
      slug: "addidas-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 300,
      countInStock: 59,
      brand: "addidas",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Adidas Cloth",
    },
    {
      _id: "4",
      name: "Addidas Track Pant",
      slug: "addidas-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 450,
      countInStock: 280,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Addidas pant Cloth",
    },
    {
      _id: "5",
      name: "Addidas Plain White T-Shirt",
      slug: "addidas-pant",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 180,
      countInStock: 120,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "6",
      name: "Check Shirt",
      slug: "Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 460,
      countInStock: 50,
      brand: "linen",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Shirts",
    },
    {
      _id: "7",
      name: "Addidas Plain Jeans",
      slug: "addidas-pant",
      category: "Pants",
      image: "/images/p7.jpg",
      price: 599,
      countInStock: 38,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "8",
      name: "Check Shirt",
      slug: "Shirt",
      category: "Shirts",
      image: "/images/p8.jpg",
      price: 380,
      countInStock: 60,
      brand: "linen",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "9",
      name: "Full Sleaves T-Shirt",
      slug: "Shirt",
      category: "Shirts",
      image: "/images/p9.jpg",
      price: 290,
      countInStock: 69,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "10",
      name: "Black Traditional Kurta",
      slug: "Kurta",
      category: "Kurtas",
      image: "/images/p10.jpg",
      price: 100,
      countInStock: 30,
      brand: "Armani",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "11",
      name: "White Traditional Kurta",
      slug: "Kurta",
      category: "Kurtas",
      image: "/images/p11.jpg",
      price: 240,
      countInStock: 90,
      brand: "Armani",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
    {
      _id: "12",
      name: "Check Shirt",
      slug: "Shirt",
      category: "Shirts",
      image: "/images/p12.jpg",
      price: 380,
      countInStock: 66,
      brand: "linen",
      rating: 4.5,
      numReviews: 10,
      description: "Good Quality Product",
    },
  ],
};

export default data;
